<?php

namespace CollegeSearch\CollegeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ApplyNowFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplyNowFormRepository extends EntityRepository
{
}
