<?php

namespace CollegeSearch\CollegeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CollegeListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollegeListRepository extends EntityRepository
{
	public function getCourses($id)
	{
		$em = $this->createQueryBuilder('c')
		->select('c.courses')
		->where('c.id=:ID')
		->setParameter('ID', $id)
		->getQuery()
		->getResult();
	
		$courses = array();
		foreach ($em as $course)
		{
			$courses = explode(",", $course['courses']);
		}
	
		return $courses;
	
	}
}
