<?php

namespace CollegeSearch\CollegeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsRepository extends EntityRepository
{
	public function getComments($collegeListId, $approved = true)
	{
		$qb = $this->createQueryBuilder('c')
		->select('c')
		->where('c.collegeList = :collegeList_id')
		->addOrderBy('c.created')
		->setParameter('collegeList_id', $collegeListId);
	
		if (false === is_null($approved))
			$qb->andWhere('c.approved = :approved')
			->setParameter('approved', $approved);
	
		return $qb->getQuery()
		->getResult();
	}
}
